md %obj_dir%

if not exist %obj_dir%\demo3d00.ali     echo .>%obj_dir%\demo3d00.ali
if not exist %obj_dir%\demo3d01.ali     echo .>%obj_dir%\demo3d01.ali
if not exist %obj_dir%\demos.ali        echo .>%obj_dir%\demos.ali
if not exist %obj_dir%\djgplibr.ali     echo .>%obj_dir%\djgplibr.ali
if not exist %obj_dir%\dosinter.ali     echo .>%obj_dir%\dosinter.ali
if not exist %obj_dir%\eng3dcon.ali     echo .>%obj_dir%\eng3dcon.ali
if not exist %obj_dir%\eng3dini.ali     echo .>%obj_dir%\eng3dini.ali
if not exist %obj_dir%\eng3dmat.ali     echo .>%obj_dir%\eng3dmat.ali
if not exist %obj_dir%\eng3dmer.ali     echo .>%obj_dir%\eng3dmer.ali
if not exist %obj_dir%\eng3dmor.ali     echo .>%obj_dir%\eng3dmor.ali
if not exist %obj_dir%\eng3dopt.ali     echo .>%obj_dir%\eng3dopt.ali
if not exist %obj_dir%\eng3dphy.ali     echo .>%obj_dir%\eng3dphy.ali
if not exist %obj_dir%\eng3dpor.ali     echo .>%obj_dir%\eng3dpor.ali
if not exist %obj_dir%\eng3dsor.ali     echo .>%obj_dir%\eng3dsor.ali
if not exist %obj_dir%\engine3d.ali     echo .>%obj_dir%\engine3d.ali
if not exist %obj_dir%\finetime.ali     echo .>%obj_dir%\finetime.ali
if not exist %obj_dir%\gamecolo.ali     echo .>%obj_dir%\gamecolo.ali
if not exist %obj_dir%\gamedriv.ali     echo .>%obj_dir%\gamedriv.ali
if not exist %obj_dir%\icosaedr.ali     echo .>%obj_dir%\icosaedr.ali
if not exist %obj_dir%\io_ports.ali     echo .>%obj_dir%\io_ports.ali
if not exist %obj_dir%\megramod.ali     echo .>%obj_dir%\megramod.ali
if not exist %obj_dir%\meteor.ali       echo .>%obj_dir%\meteor.ali
if not exist %obj_dir%\multkeys.ali     echo .>%obj_dir%\multkeys.ali
if not exist %obj_dir%\pc_mouse.ali     echo .>%obj_dir%\pc_mouse.ali
if not exist %obj_dir%\sbdriver.ali     echo .>%obj_dir%\sbdriver.ali
if not exist %obj_dir%\sb_digi.ali      echo .>%obj_dir%\sb_digi.ali
if not exist %obj_dir%\scanprof.ali     echo .>%obj_dir%\scanprof.ali
if not exist %obj_dir%\shuttle3.ali     echo .>%obj_dir%\shuttle3.ali
if not exist %obj_dir%\sveffbum.ali     echo .>%obj_dir%\sveffbum.ali
if not exist %obj_dir%\svga-io.ali      echo .>%obj_dir%\svga-io.ali
if not exist %obj_dir%\svga.ali         echo .>%obj_dir%\svga.ali
if not exist %obj_dir%\svgaeffe.ali     echo .>%obj_dir%\svgaeffe.ali
if not exist %obj_dir%\svgeffio.ali     echo .>%obj_dir%\svgeffio.ali
if not exist %obj_dir%\time_log.ali     echo .>%obj_dir%\time_log.ali
if not exist %obj_dir%\undechuf.ali     echo .>%obj_dir%\undechuf.ali
if not exist %obj_dir%\unzideco.ali     echo .>%obj_dir%\unzideco.ali
if not exist %obj_dir%\unzip.ali        echo .>%obj_dir%\unzip.ali
if not exist %obj_dir%\unzistre.ali     echo .>%obj_dir%\unzistre.ali
if not exist %obj_dir%\vehic001.ali     echo .>%obj_dir%\vehic001.ali
if not exist %obj_dir%\x29.ali          echo .>%obj_dir%\x29.ali
if not exist %obj_dir%\zip-crc.ali      echo .>%obj_dir%\zip-crc.ali
if not exist %obj_dir%\zip.ali          echo .>%obj_dir%\zip.ali
if not exist %obj_dir%\zipheade.ali     echo .>%obj_dir%\zipheade.ali
if not exist %obj_dir%\zipstrea.ali     echo .>%obj_dir%\zipstrea.ali
